Feature/1 raylib encapsulation
MisterPeModder/Bomberman-Global-Offensive pull request #105
Opened 2022-06-08 17:13 UTC by aurelenc

2022-06-09 10:28 UTC, MisterPeModder requested changes

2022-06-09 10:28 UTC, MisterPeModder commented on src/raylib/model/Mesh.hpp
> +    namespace model
`namespace raylib::model` would have saved you the trouble en indenting

2022-06-09 10:28 UTC, MisterPeModder commented on src/raylib/model/Mesh.hpp
> +            /// @param other the mesh to not copy
Documenting a deleted method's parameters makes no sense since it doesn't exist

2022-06-09 10:28 UTC, MisterPeModder commented on src/raylib/model/Mesh.hpp
> +            /// Gets the C Raylib mutable version of the mesh
> mutable

Are you sure? Looks immutable to me.

2022-06-10 06:58 UTC, TomDUVAL-MAHE approved these changes

2022-06-11 07:17 UTC, AndreasLrx requested changes
Some changes to make, lots of changes were made on the branch feature/95-Game-main-loop-create-map

2022-06-11 07:17 UTC, AndreasLrx commented on src/raylib/textures/Image.cpp
> +        const ::Image Image::asRaylib() const { return _image; }
Return a reference instead of an entire copy of the image

2022-06-11 07:17 UTC, AndreasLrx commented on src/raylib/textures/Texture2D.cpp
> +        const ::Texture2D Texture2D::asRaylib() const { return _texture; }
Return a reference instead of an entire copy of the texture.

2022-06-11 14:42 UTC, AndreasLrx approved these changes

2022-06-11 14:50 UTC, MisterPeModder approved these changes

2022-06-11 14:50 UTC, merged