Feature/9 option menu worlds
MisterPeModder/Bomberman-Global-Offensive pull request #146
Opened 2022-06-13 15:18 UTC by aurelenc

2022-06-13 15:26 UTC, MisterPeModder approved these changes

2022-06-13 15:59 UTC, MisterPeModder requested changes
The whole object-oriented architecture just to create a few worlds seems over-engineered to me.

2022-06-13 16:04 UTC, aurelenc commented
> The whole object-oriented architecture just to create a few worlds seems over-engineered to me.

no worries

2022-06-13 22:08 UTC, MisterPeModder approved these changes

2022-06-14 09:41 UTC, ZQUEMA commented on src/game/scenes/MainScene.hpp
> +    };
Rename MainScene as MainMenuScene
This is more comprehensible

2022-06-14 09:43 UTC, ZQUEMA commented on src/game/scenes/TestScene.cpp
> +static void loadTestWorld(ecs::World &world)
Rename as loadTestScene

2022-06-14 09:45 UTC, ZQUEMA requested changes
Changes are requested

2022-06-14 12:17 UTC, AndreasLrx approved these changes
Fine for me when @ZQUEMA requests are resolved.

2022-06-14 14:24 UTC, merged