Add JS-facing game debug mode
MisterPeModder/Bomberman-Global-Offensive pull request #189
Opened 2022-06-15 23:33 UTC by MisterPeModder

Closes #176

2022-06-15 23:45 UTC, AndreasLrx requested changes

2022-06-15 23:45 UTC, AndreasLrx commented on src/game/Engine.hpp
> +        void setDebugMode(bool value) noexcept;
Missing documentation

2022-06-15 23:45 UTC, aurelenc approved these changes
Works as expected on windows, haven't tested the other platforms

2022-06-15 23:55 UTC, AndreasLrx approved these changes

2022-06-16 12:13 UTC, ZQUEMA approved these changes

2022-06-16 13:12 UTC, merged