Feature/161 implement 2d auto scale
MisterPeModder/Bomberman-Global-Offensive pull request #204
Opened 2022-06-16 17:49 UTC by aurelenc

2022-06-16 18:44 UTC, AndreasLrx requested changes
Seems quite good, but the 16/9 ratio is 1280x720 not 1080x720 (sorry I missed that earlier).

2022-06-16 18:44 UTC, AndreasLrx commented on src/game/scenes/SettingsMenuScene.cpp
> +                raylib::core::Window::setSize(1080, 720);
Are those lines needed ? toggleFullScreen doesn't do the job alone ?

2022-06-16 21:14 UTC, AndreasLrx approved these changes

2022-06-16 22:51 UTC, MisterPeModder approved these changes

2022-06-17 07:37 UTC, ZQUEMA approved these changes

2022-06-17 08:30 UTC, merged