Feature/18 add sprite and song
MisterPeModder/Bomberman-Global-Offensive pull request #224
Opened 2022-06-17 15:15 UTC by TomDUVAL-MAHE

Branch for add all assets if you want

2022-06-17 15:27 UTC, aurelenc requested changes
assets/audio/musics/main_menu_theme.ogg
assets/audio/musics/game_theme.ogg
assets/audio/sounds/vlave_splash.ogg
assets/audio/sounds/raylib_splash.ogg
assets/audio/sounds/c4_explosion.ogg
assets/audio/sounds/flashbang.ogg
assets/audio/sounds/smoke.ogg
assets/audio/sounds/wins.ogg
assets/audio/sounds/vlave_splash.ogg
assets/audio/sounds/affirmative.ogg

2022-06-17 15:40 UTC, MisterPeModder approved these changes

2022-06-17 15:44 UTC, AndreasLrx approved these changes

2022-06-17 16:13 UTC, ZQUEMA approved these changes

2022-06-18 09:10 UTC, aurelenc approved these changes

2022-06-18 09:15 UTC, aurelenc approved these changes

2022-06-18 09:22 UTC, francoisbaudouin approved these changes
ok

2022-06-18 09:22 UTC, merged