Feature/76 create the hud
MisterPeModder/Bomberman-Global-Offensive pull request #238
Opened 2022-06-18 14:41 UTC by francoisbaudouin

2022-06-19 20:41 UTC, ZQUEMA requested changes
Incorrect scaling on the screen

2022-06-19 20:41 UTC, ZQUEMA commented on locales/locale_fr.po
> +msgstr "nombre de Bomb"
Bad traduction

2022-06-19 20:41 UTC, ZQUEMA commented on locales/locale_fr.po
> +msgstr "Puissance Bomb"
Bad traduction

2022-06-19 20:41 UTC, ZQUEMA commented on locales/locale_en.po
> +msgid "Bomb number"
Bombs

2022-06-19 20:41 UTC, ZQUEMA commented on src/game/components/Hud.cpp
> +
Why does this file exist?

2022-06-19 20:51 UTC, AndreasLrx requested changes

2022-06-19 20:51 UTC, AndreasLrx commented on src/game/components/Hud.hpp
> +        // Hud(Player owner, Identity id)
Trailing comments

2022-06-19 20:51 UTC, AndreasLrx commented on src/game/systems/DrawHud.hpp
> +#endif /*!DRAW_HUD_HPP_*/
Missing newline

2022-06-19 20:51 UTC, AndreasLrx commented on src/localization/Resources.hpp
> +            constexpr ResourceString rsNoclip("NoClip");
Rename to Wall pass

2022-06-19 21:34 UTC, AndreasLrx approved these changes

2022-06-22 11:40 UTC, AndreasLrx commented
Duplicate #298

2022-06-22 11:40 UTC, closed without merging