Add scoped Mode3D and Drawing classes in raylib::core::scopes namespace
MisterPeModder/Bomberman-Global-Offensive pull request #34
Opened 2022-05-19 11:25 UTC by AndreasLrx

Multiple raylib drawing functions need a begin and end function call. The namespace scopes will contain classes using RAII model to call the begin... on construction and end... on destruction.
It avoid calling begin... and forgetting the associated end function.

Resolve: #31

2022-05-19 12:05 UTC, aurelenc requested changes

2022-05-19 12:05 UTC, aurelenc commented on src/main.cpp
>      raylib::core::Camera3D *camera = reinterpret_cast<raylib::core::Camera3D *>(arg);
You can delete this line now

2022-05-19 12:05 UTC, aurelenc approved these changes

2022-05-19 15:44 UTC, MisterPeModder approved these changes
Woundn't `scoped` be a better name f

2022-05-19 15:44 UTC, MisterPeModder commented on src/raylib/core/CMakeLists.txt
> +    ${SRCROOT}/Scopes.hpp
Wouldn't `scoped` be a better name for the name of this namespace and file.
Moreover, should files that does not describe a single class have an UpperCamelCase name? the name `Scopes.cpp` suggests that there is a class named `Scopes` available.

2022-05-19 15:55 UTC, TomDUVAL-MAHE approved these changes

2022-05-20 08:05 UTC, MisterPeModder approved these changes

2022-05-20 08:38 UTC, ZQUEMA approved these changes

2022-05-20 08:38 UTC, merged