Feature/1 raylib encapsulation textures
MisterPeModder/Bomberman-Global-Offensive pull request #40
Opened 2022-05-24 14:05 UTC by TomDUVAL-MAHE

Check Class Texture2D Encapsulation
Don't kill the branch please i make Image class encapsulation on it

2022-05-24 14:55 UTC, MisterPeModder requested changes

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +** Bomberman-Global-Offensive
Bomberman: Global Offensive

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +                    0;
Did you mean `,`?

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +            ///@param position The position of the texture on the screen.
Missing space after `///`

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +            void loadTextureFromImage(Image image);
You are passing `Image` by copy, prefer `Image const &` or `Image &` if you want it to be mutable.

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +            void updateTexture(const void *pixels);
`std::span<T>` would be better suited here, the type of `T` may be `char`, or `uint32_t`

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +            void updateTextureRec(Rectangle rec, const void *pixels);
same as above, `std::span<T> pixels`

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +            /// It sets the texture filter.
`/// Sets the texture filter`

Please explain what `filter` is in the documentation, and if is a constant, consider using an enum instead.

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +            void setTextureWrap(int wrap);
Is `wrap` a boolean by chance ?

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +            void drawTextureEx(Vector2 position, float rotation, float scale, Color tint);
The above functions looks like they could be overloads of each other.

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.cpp
> +        Texture2D::~Texture2D()
You can use `~Texture2D() = default` in `Texture2D.hpp` instead of defining an empty destructor

2022-05-24 14:55 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.cpp
> +        Texture2D::Texture2D(Vector2 position, char *fileName)
Prefer the following syntax for initializing members:
```c++
Texture2D::Texture2D(Vector2 position, char *fileName) : _fileName(fileName), _position(position), ...
```

2022-05-24 18:14 UTC, TomDUVAL-MAHE commented on src/raylib/textures/Texture2D.hpp
> +            void setTextureWrap(int wrap);
It doesn't write in the documentation

2022-05-24 18:35 UTC, AndreasLrx commented on src/raylib/textures/Image.hpp
> +            bool exportImage(const char *fileName);
std::string_view

2022-05-24 18:36 UTC, AndreasLrx commented on src/raylib/textures/Image.hpp
> +            void imageFormat(int newFormat);
What is the format parameter ? Is there more precision in the raylib documentation ?

2022-05-24 18:38 UTC, AndreasLrx commented on src/raylib/textures/Image.hpp
> +            Color getColor();
What is the color of the image ? 
The mean color ?
Or should it be an array of colors ?

2022-05-24 18:38 UTC, AndreasLrx commented on src/raylib/textures/Image.hpp
> +            char *fileName;
Replace by std::string

2022-05-25 13:20 UTC, ZQUEMA requested changes
There are a few changes that need to be made before

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/shapes/Circle.hpp
> +            float _z;
For all positional characteristics: use one Vector3 instead of three separate variables.

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/shapes/Circle.hpp
> +            void setPosition(float x, float y, float z = 0);
For all positional characteristics: use one Vector3 instead of three separate variables.

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/shapes/Circle.hpp
> +            Circle(float x = 0, float y = 0, float z = 0, float radius = 0, Color color = {0, 0, 0, 0});
For all positional characteristics: use one Vector3 instead of three separate variables.

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/shapes/Circle.cpp
> +            _z = z;
For all positional characteristics: use one Vector3 instead of three separate variables.

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/textures/Image.cpp
> +        Image::Image(std::string fileName, Vector2 position, Color *color) :_fileName(fileName), _position(position), _color(color)
use const std::filesystem::path &filepath instead of std::string fileName

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/textures/Image.hpp
> +            std::string _fileName;
use const std::filesystem::path &filepath instead of std::string fileName

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/textures/Image.hpp
> +            Image(std::string fileName, Vector2 position = {}, Color *color = {});
use const std::filesystem::path &filepath instead of std::string fileName

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/textures/Image.cpp
> +        bool Image::exportImage(const std::string fileName) { return ExportImage(_image, fileName.c_str()); }
use const std::filesystem::path &filepath instead of std::string fileName

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/textures/Texture2D.cpp
> +        Texture2D::Texture2D(std::string fileName, Vector2 position) : _fileName(fileName), _position(position)
use const std::filesystem::path &filepath instead of std::string fileName

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/textures/Texture2D.hpp
> +            std::string _fileName;
use const std::filesystem::path &filepath instead of std::string fileName

2022-05-25 13:20 UTC, ZQUEMA commented on src/raylib/textures/Texture2D.hpp
> +            Texture2D(std::string fileName, Vector2 position = {});
use const std::filesystem::path &filepath instead of std::string fileName

2022-05-29 16:57 UTC, aurelenc commented
I think the circle already got updated in the #29 branch

2022-05-30 07:37 UTC, MisterPeModder requested changes
`std::span<uint32_t> pixels` should not be passed by pointer.

2022-05-30 07:37 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.cpp
> +        void Texture2D::updateTexture(std::span<uint32_t> *pixels) { UpdateTexture(_texture, pixels); }
`std::span<uint32_t> pixels` should not be passed by pointer.

2022-05-30 07:37 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.cpp
> +        void Texture2D::updateTextureRec(Rectangle &rec, std::span<uint32_t> *pixels)
`std::span<uint32_t> pixels` should not be passed by pointer.

2022-05-30 07:37 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +            void updateTexture(std::span<uint32_t> *pixels);
`std::span<uint32_t> pixels` should not be passed by pointer.

2022-05-30 07:37 UTC, MisterPeModder commented on src/raylib/textures/Texture2D.hpp
> +            void updateTextureRec(Rectangle &rec, std::span<uint32_t> *pixels);
`std::span<uint32_t> pixels` should not be passed by pointer.

2022-05-30 11:03 UTC, ZQUEMA approved these changes

2022-05-30 11:35 UTC, aurelenc approved these changes

2022-05-30 12:23 UTC, AndreasLrx approved these changes

2022-05-30 13:17 UTC, MisterPeModder approved these changes

2022-05-30 13:18 UTC, merged