Add dynamic bit set helper class
MisterPeModder/Bomberman-Global-Offensive pull request #52
Opened 2022-05-26 20:53 UTC by MisterPeModder

Resolves #51

2022-05-27 08:13 UTC, AndreasLrx requested changes

2022-05-27 10:17 UTC, MisterPeModder commented on src/util/BitSet.hpp
> +    /// Mimimics the API of std::bitset but with the dynamic properties of std::vector<bool>
Indeed

2022-05-27 10:37 UTC, AndreasLrx approved these changes

2022-05-30 11:09 UTC, ZQUEMA approved these changes

2022-05-30 11:18 UTC, merged