Raylib keyboard/gamepad encapsulation
MisterPeModder/Bomberman-Global-Offensive pull request #86
Opened 2022-05-31 07:40 UTC by AndreasLrx

Resolves #57

2022-05-31 07:47 UTC, MisterPeModder requested changes

2022-05-31 07:47 UTC, MisterPeModder commented on src/raylib/core/Keyboard.hpp
> +                APOSTROPHE = 39,    // Key: '
Use `//<` to document the keys.

2022-06-01 12:22 UTC, ZQUEMA approved these changes

2022-06-02 09:10 UTC, MisterPeModder approved these changes

2022-06-02 09:11 UTC, merged