Procedural map generation
MisterPeModder/Bomberman-Global-Offensive pull request #87
Opened 2022-05-31 08:11 UTC by AndreasLrx

Generate a map randomly filled. It can use cellular automata (maybe overkill here I admit).

Resolves: #11

2022-05-31 12:08 UTC, MisterPeModder requested changes
Looks good, you a few things to change here and there.

2022-05-31 12:08 UTC, MisterPeModder commented on src/game/map/cellular/Grid.cpp
> +} // namespace bomberman
Missing a newline here

2022-05-31 12:08 UTC, MisterPeModder commented on src/game/map/cellular/Grid.hpp
> +                /// @return true If the cell is filled.
Use `@retval` if you want to specify return values

2022-05-31 12:08 UTC, MisterPeModder commented on src/game/map/cellular/Grid.hpp
> +                unsigned char getNeighbours(size_t x, size_t y) const;
We are using American English in this codebase.

2022-05-31 12:08 UTC, MisterPeModder commented on src/game/map/cellular/Rule.cpp
> +    }     // namespace map
You have extra spaces between `}` and `// namespace`

2022-05-31 12:08 UTC, MisterPeModder commented on src/game/map/cellular/Rule.hpp
> +                class RuleInvalid : public std::runtime_error {
Do you mean `InvalidRule` ?

2022-06-01 12:58 UTC, ZQUEMA approved these changes

2022-06-02 09:09 UTC, merged