Game settings and player profiles
MisterPeModder/Bomberman-Global-Offensive pull request #90
Opened 2022-06-02 09:20 UTC by AndreasLrx

Add global game settings and player profiles.

### Game settings

In class game::settings::Settings.
Stores:
- Music volume [0-100], default is 100
- Sound effect (SFX) volume [0-100], default is 100
- Target framerate [0...], default is 60
- Screen resolution, constraints not yet defined, default is 1280x720
- Fullscreen (true/false), default is false

The configuration is saved in the file "settings/settings.cfg".

### Player profiles

In class game::settings::Profile
Stores:
- Profile name
- Keyboard keybinds
- Gamepad keybinds

The configuration is saved in the file "settings/profiles/profile_[id].cfg".

On load, if a file doesn't exist or a value is invalid it is ignored (a warning is sent in the logger) and default value(s) is used.
On save, if the directory tree doesn't exists it is created (settings and profiles directories).

### Unit tests

The Profiles and Keybinds class aren't tested yet because I'm not sure of the current way to manage the keybinds. It will be discussed in the next weekly meeting (03/06/22 morning).

2022-06-03 08:45 UTC, MisterPeModder requested changes

2022-06-03 08:45 UTC, MisterPeModder commented on src/game/GameAction.hpp
> +        PAUSE,
I would add an `ACTION` and maybe a `BACK` key to navigate between menus.

2022-06-03 08:45 UTC, MisterPeModder commented on src/game/settings/GamepadInput.cpp
> +} // namespace game
You forgot a newline

2022-06-03 08:45 UTC, MisterPeModder commented on src/game/settings/GamepadInput.hpp
> +            bool operator<(const GamepadInput &other) const;
The C++20 way is `<=>`

2022-06-03 08:45 UTC, MisterPeModder commented on src/game/settings/Settings.cpp
> +                height = std::stof(value.data() + value.find('x') + 1);
I don't think non-integral resolutions should be allowed

2022-06-03 08:45 UTC, MisterPeModder commented on src/game/settings/Settings.hpp
> +            class InvalidSettingsValue : public std::logic_error {
`InvalidSettingsValues` should inherit `std::runtime_error`, since it can be triggered by the users

2022-06-03 08:45 UTC, MisterPeModder commented on src/util/util.cpp
> +} // namespace util
Missing a newline here

2022-06-03 08:45 UTC, MisterPeModder commented on tests/settings/test_GamepadInput.cpp
> +}
Missing a newline

2022-06-03 08:45 UTC, MisterPeModder commented on tests/util/test_loadConfigFile.cpp
> +}
Missing a newline

2022-06-07 08:00 UTC, ZQUEMA approved these changes

2022-06-07 08:49 UTC, MisterPeModder approved these changes
mighty fine, mate!

2022-06-07 08:49 UTC, merged