Feature/1 raylib encapsulation audio
MisterPeModder/Bomberman-Global-Offensive pull request #91
Opened 2022-06-03 06:51 UTC by francoisbaudouin

2022-06-03 07:44 UTC, TomDUVAL-MAHE commented on src/raylib/core/Sound.hpp
> +            bool isSoundPlaying();
The Class is Sound, you don't have need to say "isSoundPlaying" you can use isPlaying. We know that function is use on Sound Object.

2022-06-03 07:44 UTC, TomDUVAL-MAHE commented on src/raylib/core/Sound.hpp
> +            void unloadSound();
Same

2022-06-03 07:44 UTC, TomDUVAL-MAHE commented on src/raylib/core/Sound.hpp
> +            void playSound();
Same

2022-06-03 07:44 UTC, TomDUVAL-MAHE commented on src/raylib/core/Sound.hpp
> +            void stopSound();
Same

2022-06-03 07:45 UTC, TomDUVAL-MAHE commented on src/raylib/core/Sound.hpp
> +            void pauseSound();
Same

2022-06-03 07:45 UTC, TomDUVAL-MAHE commented on src/raylib/core/Sound.hpp
> +            void resumeSound();
Same

2022-06-03 07:45 UTC, TomDUVAL-MAHE commented on src/raylib/core/Sound.hpp
> +            void setSoundVolume(float volume);
Same

2022-06-03 07:46 UTC, TomDUVAL-MAHE commented on src/raylib/core/Audio.hpp
> +            static void initAudioDevice();
The Class is Audio, you don't have need to say "initAudioDevice" you can use initDevice. We know that function is use on Audio Object.

2022-06-03 07:46 UTC, TomDUVAL-MAHE commented on src/raylib/core/Audio.hpp
> +            static void closeAudioDevice();
Same

2022-06-03 07:46 UTC, TomDUVAL-MAHE commented on src/raylib/core/Audio.hpp
> +            static bool isAudioDeviceReady();
Same

2022-06-03 07:47 UTC, aurelenc requested changes

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Audio.cpp
> +        void Audio::initAudioDevice(void) { InitAudioDevice(); }
initDevice()

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Audio.cpp
> +        void Audio::closeAudioDevice(void) { CloseAudioDevice(); }
closeDevice()

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Audio.cpp
> +        bool Audio::isAudioDeviceReady() { return IsAudioDeviceReady(); }
isDeviceReady()

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Sound.cpp
> +        void Sound::unloadSound() { UnloadSound(_music); }
UnloadSound(_music) in destructor

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Sound.cpp
> +        bool Sound::isSoundPlaying() { return IsSoundPlaying(_music); }
isPlaying()

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Sound.cpp
> +        void Sound::playSound() { PlaySound(_music); }
play()

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Sound.cpp
> +        void Sound::stopSound() { StopSound(_music); }
stop()

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Sound.cpp
> +        void Sound::pauseSound() { PauseSound(_music); }
pause()

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Sound.cpp
> +        void Sound::resumeSound() { ResumeSound(_music); }
resume()

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Sound.cpp
> +        void Sound::setSoundVolume(float volume) { SetSoundVolume(_music, volume); }
setVolume()

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Audio.hpp
> +#endif /*RAYLIB_CORE_AUDIO_HPP_*/
New line

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Sound.cpp
> +} // namespace raylib
New line

2022-06-03 07:47 UTC, aurelenc commented on src/raylib/core/Sound.hpp
> +#endif /*RAYLIB_CORE_MUSIC_HPP_*/
New line

2022-06-06 07:40 UTC, ZQUEMA approved these changes

2022-06-07 14:32 UTC, AndreasLrx requested changes

2022-06-07 14:32 UTC, AndreasLrx commented on src/main.cpp
> +    audio.initDevice();
Create a new Scoped class instead of doing initDevice/closeDevice.
See raylib/core/scoped.hpp.

2022-06-07 14:32 UTC, AndreasLrx commented on src/raylib/core/Sound.hpp
> +            ::Sound _music;
A sound isn't a music, there is a specific struct Music in the raylib which might also be encapsulated later.
Rename the attribute _music -> _sound

2022-06-07 18:52 UTC, MisterPeModder approved these changes
Looks good to me, just fix that formatting error and it will be fine!

2022-06-08 07:46 UTC, AndreasLrx approved these changes

2022-06-08 08:15 UTC, aurelenc approved these changes

2022-06-08 08:16 UTC, merged