Move raylib logger in raylib namespace
MisterPeModder/Bomberman-Global-Offensive pull request #94
Opened 2022-06-03 08:46 UTC by AndreasLrx

Resolves #36

2022-06-03 08:47 UTC, AndreasLrx commented
PR #90 must be merged before this one.

2022-06-07 11:17 UTC, ZQUEMA approved these changes

2022-06-07 18:46 UTC, MisterPeModder requested changes
You forgot to include `<cstdarg>`

2022-06-07 18:46 UTC, MisterPeModder commented on src/raylib/logger.cpp
> +    static void raylibLogger(int msgType, const char *text, va_list args)
Please include `<cstdarg>` to use `va_list`.

2022-06-07 19:28 UTC, MisterPeModder approved these changes

2022-06-07 21:42 UTC, merged